sm6250-common: remove conflict overlay
[100% 183/183] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: vendor/aosp/rro_overlays/NoCutoutOverlay/Android.bp:1:1: module "NoCutoutOverlay" already defined
       device/xiaomi/sm6250-common/rro_overlays/NoCutoutOverlay/Android.bp:15:1 <-- previous definition here
12:07:23 soong bootstrap failed with: exit status 1

---------------------------